name: 'Badges'

on:
  push:
    branches: [main]

jobs:
  badge:
    name: Generate badges
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install devDependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Generate badges SVG
        run: npm run badges

      - name: Upload badges as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: docs/badges/*
          if-no-files-found: error
      
      - name: Commit badges
        continue-on-error: true
        run: |
          git add docs/badges/*
          git commit -m "Update badges"
        
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges