name: Badges

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  badge:
    name: Generate badges
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install devDependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Generate badges SVG
        run: npm run badges

      - name: Upload badges as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: *-badge.svg
          if-no-files-found: error
      
      - name: Commit badges
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan badges
          git rm --cached $(git ls-files)
          git add *-badge.svg -f
          git commit -m "Update badges"
          git push origin badges