name: Badges

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  badge:
    name: Generate badges
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: vx.x.x

      - name: Generate badges SVG
        run: deno task prepare-badges

      - name: Upload badges as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: "badges/*"
          if-no-files-found: error

      - name: Commit badges
        continue-on-error: true
        run: |
          git config user.name Github Actions
          git config user.email github-actions@github.com
          git checkout --orphan badges
          git rm --cached $(git ls-files)
          git add badges/* -f
          git commit -m "chore: update badges"
          git push origin badges --force
