name: Publish Node

on:
  release:
    types:
      - "published"

jobs:
  deno-workflow:
    uses: ./.github/workflows/deno.yml

  node-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup repo
      uses: actions/checkout@v2
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1.1.0
      with:
        deno-version: vx.x.x

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Get tag version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag_version
      run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Prepare node version
      run: deno run --allow-env=HOME,DENO_AUTH_TOKENS,XDG_CACHE_HOME,DENO_DIR --allow-read --allow-write=./node,$HOME/.cache/deno --allow-run=npm scripts/dnt.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
      
    - name: Publish node version to npm
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: cd node && npm publish