name: Publish Node

on:
  release:
    types:
      - "published"

jobs:
  deno-workflow:
    uses: ./.github/workflows/deno.yml

  node-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: vx.x.x

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Prepare and publish node packages
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG_VERSION: ${{steps.get_tag_version.outputs.TAG_VERSION}}
        run: >
          ((deno task prepare-crayon        $TAG_VERSION && cd node_crayon           && npm publish) || (cd src)) &&
          ((deno task prepare-chalk-aliases $TAG_VERSION && cd node_chalk_aliases && npm publish) || true) &&
          ((deno task prepare-css-keywords  $TAG_VERSION && cd node_css_keywords  && npm publish) || true) &&
          ((deno task prepare-literal       $TAG_VERSION && cd node_literal       && npm publish) || true)
