name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 21.x]

    steps:
      - uses: actions/checkout@v3
      - run: 'echo ''{ "type": "module" }'' > package.json'
      - run: npx jsr add @beast/compat @std/assert
      - run: npx --yes tsx --test **/*.test.ts
