name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [21.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: 'echo ''{ "type": "module" }'' > package.json'
      - run: npx jsr add @beast/compat @std/assert
      - run: npx --yes tsx --test **/*.test.ts
